#!/bin/bash

docker run --rm \
  -e "OS_USERNAME=$OS_USERNAME" \
  -e "OS_PASSWORD=$OS_PASSWORD" \
  -e "OS_AUTH_URL=$OS_AUTH_URL" \
  -e "OS_PROJECT_NAME=$OS_PROJECT_NAME" \
  -e "OS_USER_DOMAIN_NAME=$OS_USER_DOMAIN_NAME" \
  -e "OS_PROJECT_DOMAIN_NAME=$OS_PROJECT_DOMAIN_NAME" \
  -e "OS_IDENTITY_API_VERSION=$OS_IDENTITY_API_VERSION" \
  -v "${HOME}:${HOME}" \
  celebdor/openstack:latest "$(id -un)" "$(id -u)" "${HOME}" "$(pwd)" "$@"
